# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.cache/wt [current_project]
set_property parent.project_path /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-35:part0:1.0 [current_project]
set_property ip_repo_paths /home/rv/riscv/e300artydevkit/obj/ip [current_project]
set_property ip_output_repo /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.srcs/sources_1/e300artydevkit/rocket-chip/src/main/resources/vsrc/AsyncResetReg.v
  /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.srcs/sources_1/e300artydevkit/ipwrapper/Blackbox_BlkDualBram.v
  /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.srcs/sources_1/e300artydevkit/fpga-shells/xilinx/common/vsrc/PowerOnResetFPGAOnly.v
  /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.srcs/sources_1/e300artydevkit/sifive-blocks/vsrc/SRLatch.v
  /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.srcs/sources_1/e300artydevkit/rocket-chip/src/main/resources/vsrc/plusarg_reader.v
  /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.srcs/sources_1/e300artydevkit/sifive.freedom.everywhere.e300artydevkit.E300ArtyDevKitConfig.rom.v
  /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.srcs/sources_1/e300artydevkit/sifive.freedom.everywhere.e300artydevkit.E300ArtyDevKitConfig.v
}
read_ip -quiet /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.srcs/sources_1/ip/reset_sys/reset_sys.xci
set_property used_in_implementation false [get_files -all /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.srcs/sources_1/ip/reset_sys/reset_sys_board.xdc]
set_property used_in_implementation false [get_files -all /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.srcs/sources_1/ip/reset_sys/reset_sys.xdc]

read_ip -quiet /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.srcs/sources_1/ip/mmcm/mmcm.xci
set_property used_in_implementation false [get_files -all /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.srcs/sources_1/ip/mmcm/mmcm_board.xdc]
set_property used_in_implementation false [get_files -all /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.srcs/sources_1/ip/mmcm/mmcm.xdc]
set_property used_in_implementation false [get_files -all /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.srcs/sources_1/ip/mmcm/mmcm_ooc.xdc]

read_ip -quiet /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.srcs/constrs_1/imports/constraints/arty-config.xdc
set_property used_in_implementation false [get_files /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.srcs/constrs_1/imports/constraints/arty-config.xdc]

read_xdc /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.srcs/constrs_1/imports/constraints/arty-master.xdc
set_property used_in_implementation false [get_files /home/rv/riscv/e300artydevkit/E300ArtyDevKitFPGAChip.srcs/constrs_1/imports/constraints/arty-master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top E300ArtyDevKitFPGAChip -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef E300ArtyDevKitFPGAChip.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file E300ArtyDevKitFPGAChip_utilization_synth.rpt -pb E300ArtyDevKitFPGAChip_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
